### ISSUE TITLE
Package and Release

### ISSUE THREAD

**Issue by rockymeza** [fusionbox/eek#5]
What do we need to do in order to get this on to PyPI?  Here is a list of things that I can think of off the top of my head:
- [ ] Do we want lxml or BeatifulSoup?
- [ ] If we choose BeautifulSoup, we should upgrade to bs4 and install_requires it instead of bundling.
- [ ] I just wanted to figure out real quick if we have unicode support, we appear to use the built-in csv module which does not have unicode support.

**Comment by gavinwahl** [comment]
- lxml is hard to install on a mac
- unicode is supported

**Comment by rockymeza** [comment]
So BeautifulSoup then?  Should we upgrade to bs4?

**Comment by gavinwahl** [comment]
upgraded to bs4, added optional support for lxml if it's installed
